### ISSUE TITLE
[Bug] The category menus, among several other things (i.e. search bar) have not worked at all since the new update. 

### ISSUE THREAD

**Issue by firey828** [AeonSake/acnh-catalogue-issues#6]
**Describe the bug**
Exactly what's written on the tin. From the tidbit of conversation on the ACNH Info discord immediately following the developer announcing the latest update, several other users are having this issue as well.

**To Reproduce**
1. Go to https://catalogue.ac/
2. Hover over 'Categories' until the category menu appears
3. Click any category (for example, "Furniture" or even specifically "Housewares")

**Expected behavior**
Prior to update, following the steps above would lead to the respective item listing. 

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser: Safari
 - Version: Safari 12.1.2

**Comment by AeonSake** [comment]
Hey there...very strange issue. I cannot reproduce the issue, even with the exact same browser/OS. I didn't change anything about the menu behavior in the recent update.
Could you please provide me with the console logs? You can show that by enabling the develop menu (`Settings > Advanced > Show Develop menu in menu bar`) and pressing `CMD+ALT+C`.

**Comment by firey828** [comment]
Here.

`TypeError: t.replaceAll is not a function. (In 't.replaceAll("{"+e+"}",arguments[e])', 't.replaceAll' is undefined)`

**Comment by AeonSake** [comment]
Oh damn, I missed that. Thanks a lot! Should be fixed now.

**Comment by firey828** [comment]
Still not working on my end, looks like the same error too. Thanks for the quick response though btw, appreciate it

**Comment by AeonSake** [comment]
Ah yes, sorry forgot to mention that you have to clear your cache for the changes/fix to apply (`CMD+ALT+E`).
Cache rules are set to 4h after which the issue should be resolved too if you don't clear your cache.
